server:
  port: 4001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1000.com:1000/eureka,http://eureka1001.com:1001/eureka #,http://eureka1002.com:1002/eureka

  instance:
    instance-id: user2
    prefer-ip-address: true #此实例注册到eureka服务中心显示ip地址
    lease-renewal-interval-in-seconds: 20 #此实例每间隔1秒向服务中心发送心跳
    lease-expiration-duration-in-seconds: 50 # 此实例5秒后还没有向服务中心发送心跳，标志着服务中心可以把此实例剔除
spring:
  application:
    name: user
    #在Spring - cloud Dalston 版本之后就默认关闭了，如果要打开则需要设置true
feign:
  hystrix:
    enabled: true
    
---
spring:
  profiles: test
server:
  port: 4002
---
spring:
  profiles: pre
server:
  port: 4003    